backend:
  name: git-gateway
  repo: 'imbalacoop/imbala'
  squash_merges: true

site_url: 'https://imbala.community'

publish_mode: editorial_workflow
media_folder: '/images/uploads'

collections:
  - name: 'test'
    label: 'Test'
    folder: 'src/_data/test.json'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
# collections:
#   - name: 'menu'
#     label: 'Menu'
#     folder: 'site/_data/menu.json'
#     extension: 'json'
#     create: true
#     delete: false
#     editor:
#       preview: false

#     files:
#       - name: 'nav'
#         label: 'Navigation'
#         file: 'src/site/_data/nav.json'
#         description: `Nav`
#         fields:
#           - label: 'English'
#             name: 'en'
#             widget: 'object'
#             fields:
#               - { label: 'About', name: 'about', widget: 'string' }
#               - { label: 'Cafe', name: 'cafe', widget: 'string' }
#               - { label: 'Join', name: 'join', widget: 'string' }
#               - { label: 'Address', name: 'address', widget: 'string' }
